on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo 'flags=--snapshot' >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
